// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace Common
{

    public class ConfigOptions : IOptions<ConfigOptions>
    {
        ConfigOptions IOptions<ConfigOptions>.Value => this;

        [JsonProperty("WebServiceUrl")]
        public WebServiceUrl WebServiceUrl { get; set; }

        [JsonProperty("Terminal")]
        public Terminal Terminal { get; set; }

        [JsonProperty("ENPS")]
        public ENPS ENPS { get; set; }

        [JsonProperty("UI")]
        public UI UI { get; set; }

        [JsonProperty("VoIP")]
        public VoIP VoIP { get; set; }

        [JsonProperty("ProgressiveDownload")]
        public IList<ProgressiveDownload> ProgressiveDownload { get; set; }

        [JsonProperty("BasicMode")]
        public BasicMode BasicMode { get; set; }

        [JsonProperty("Vlc")]
        public Vlc Vlc { get; set; }

        [JsonProperty("DeckLink")]
        public DeckLink DeckLink { get; set; }

        [JsonProperty("VideoFeedback")]
        public VideoFeedback VideoFeedback { get; set; }

        [JsonProperty("WebREncoder")]
        public WebREncoder WebREncoder { get; set; }

        [JsonProperty("FecTransport")]
        public FecTransport FecTransport { get; set; }

        [JsonProperty("Setting")]
        public Setting Setting { get; set; }

        [JsonProperty("Alert")]
        public Alert Alert { get; set; }

        [JsonProperty("AutoRecord")]
        public AutoRecord AutoRecord { get; set; }

        [JsonProperty("LogoOverlay")]
        public LogoOverlay LogoOverlay { get; set; }

        [JsonProperty("LiveEncoder")]
        public LiveEncoder LiveEncoder { get; set; }

        [JsonProperty("ExEncoder")]
        public ExEncoder ExEncoder { get; set; }

        [JsonProperty("Producer")]
        public Producer Producer { get; set; }

        [JsonProperty("WebSite")]
        public WebSite WebSite { get; set; }

        [JsonProperty("R2TPDSWrapper")]
        public R2TPDSWrapper R2TPDSWrapper { get; set; }

        [JsonProperty("TokenSystem")]
        public TokenSystem TokenSystem { get; set; }

        [JsonProperty("SmartCaption")]
        public SmartCaption SmartCaption { get; set; }

        [JsonProperty("Ftp")]
        public Ftp Ftp { get; set; }

        [JsonProperty("GridEncoder")]
        public GridEncoder GridEncoder { get; set; }

        [JsonProperty("WebRTC")]
        public WebRTC WebRTC { get; set; }

        [JsonProperty("IFB")]
        public IFB IFB { get; set; }
    }
    public class CommandCenter
    {

        [JsonProperty("WebSocket")]
        public string WebSocket { get; set; }
    }

    public class GridSwitch
    {

        [JsonProperty("WebSocket")]
        public string WebSocket { get; set; }
    }

    public class WebServiceUrl
    {

        [JsonProperty("CommandCenter")]
        public CommandCenter CommandCenter { get; set; }

        [JsonProperty("GridSwitch")]
        public GridSwitch GridSwitch { get; set; }
    }

    public class Terminal
    {

        [JsonProperty("PSIP")]
        public string PSIP { get; set; }

        [JsonProperty("PSPort")]
        public string PSPort { get; set; }

        [JsonProperty("ExternalIP")]
        public string ExternalIP { get; set; }

        [JsonProperty("ExternalPort")]
        public string ExternalPort { get; set; }

        [JsonProperty("LocalIP")]
        public string LocalIP { get; set; }

        [JsonProperty("LocalPort")]
        public string LocalPort { get; set; }

        [JsonProperty("URL")]
        public string URL { get; set; }

        [JsonProperty("PlayURL")]
        public string PlayURL { get; set; }

        [JsonProperty("TPDSWebUrl")]
        public string TPDSWebUrl { get; set; }

        [JsonProperty("TPDSSendStatus")]
        public string TPDSSendStatus { get; set; }

        [JsonProperty("TPDSSendThumbnail")]
        public string TPDSSendThumbnail { get; set; }

        [JsonProperty("TPDSSendHeartBeat")]
        public string TPDSSendHeartBeat { get; set; }

        [JsonProperty("TPDSGetThumbnailInterval")]
        public string TPDSGetThumbnailInterval { get; set; }

        [JsonProperty("TPDSSendThumbnailInterval")]
        public string TPDSSendThumbnailInterval { get; set; }

        [JsonProperty("TPDSSendStatusInterval")]
        public string TPDSSendStatusInterval { get; set; }

        [JsonProperty("TPDSSendHeartBeatInterval")]
        public string TPDSSendHeartBeatInterval { get; set; }

        [JsonProperty("LiveSwitchWebUrl")]
        public string LiveSwitchWebUrl { get; set; }

        [JsonProperty("LiveSwitchGetPreloadInterval")]
        public string LiveSwitchGetPreloadInterval { get; set; }

        [JsonProperty("GridUseLocalConfig")]
        public string GridUseLocalConfig { get; set; }

        [JsonProperty("GridWebUrl")]
        public string GridWebUrl { get; set; }

        [JsonProperty("GridPeerInfoWebUrl")]
        public string GridPeerInfoWebUrl { get; set; }

        [JsonProperty("ShowExt")]
        public string ShowExt { get; set; }

        [JsonProperty("ShowGrid")]
        public string ShowGrid { get; set; }

        [JsonProperty("AutoDownload")]
        public string AutoDownload { get; set; }

        [JsonProperty("ShowInfo")]
        public string ShowInfo { get; set; }

        [JsonProperty("Tab")]
        public string Tab { get; set; }

        [JsonProperty("SpeedScaleQuality")]
        public string SpeedScaleQuality { get; set; }
    }

    public class ENPS
    {

        [JsonProperty("DestRootFolder")]
        public string DestRootFolder { get; set; }
    }

    public class CEF
    {

        [JsonProperty("DevTool")]
        public string DevTool { get; set; }
    }

    public class WebBrowser
    {

        [JsonProperty("CEF")]
        public CEF CEF { get; set; }
    }

    public class PackSource
    {

        [JsonProperty("SortRule")]
        public string SortRule { get; set; }
    }

    public class PeerList
    {

        [JsonProperty("Visible")]
        public string Visible { get; set; }
    }

    public class UI
    {

        [JsonProperty("WebBrowser")]
        public WebBrowser WebBrowser { get; set; }

        [JsonProperty("PackSource")]
        public PackSource PackSource { get; set; }

        [JsonProperty("PeerList")]
        public PeerList PeerList { get; set; }
    }

    public class Pack
    {

        [JsonProperty("MinimumVersion")]
        public string MinimumVersion { get; set; }
    }

    public class VoIP
    {

        [JsonProperty("ServerUrl")]
        public string ServerUrl { get; set; }

        [JsonProperty("Pack")]
        public Pack Pack { get; set; }
    }

    public class ProgressiveDownload
    {

        [JsonProperty("ConvertCmdFormat")]
        public string ConvertCmdFormat { get; set; }

        [JsonProperty("AutoConvertTStoMOV")]
        public string AutoConvertTStoMOV { get; set; }

        [JsonProperty("AutoConvertFileFormat")]
        public string AutoConvertFileFormat { get; set; }
    }

    public class Interview
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }
    }

    public class Normal
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }
    }

    public class FastMoving
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }
    }

    public class SD
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }
    }

    public class TapeFeed
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }
    }

    public class User1
    {

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }

        [JsonProperty("IsUserDefine")]
        public string IsUserDefine { get; set; }

        [JsonProperty("VideoMode")]
        public string VideoMode { get; set; }
    }

    public class User2
    {

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Bitrate")]
        public string Bitrate { get; set; }

        [JsonProperty("Delay")]
        public string Delay { get; set; }

        [JsonProperty("IsUserDefine")]
        public string IsUserDefine { get; set; }

        [JsonProperty("VideoMode")]
        public string VideoMode { get; set; }
    }

    public class BasicMode
    {

        [JsonProperty("Interview")]
        public Interview Interview { get; set; }

        [JsonProperty("Normal")]
        public Normal Normal { get; set; }

        [JsonProperty("FastMoving")]
        public FastMoving FastMoving { get; set; }

        [JsonProperty("SD")]
        public SD SD { get; set; }

        [JsonProperty("TapeFeed")]
        public TapeFeed TapeFeed { get; set; }

        [JsonProperty("User1")]
        public User1 User1 { get; set; }

        [JsonProperty("User2")]
        public User2 User2 { get; set; }
    }

    public class Vlc
    {

        [JsonProperty("EnableSDI")]
        public string EnableSDI { get; set; }

        [JsonProperty("DesktopParameters")]
        public string DesktopParameters { get; set; }

        [JsonProperty("SdiParameters")]
        public string SdiParameters { get; set; }
    }

    public class DeckLink
    {

        [JsonProperty("MatchInput")]
        public string MatchInput { get; set; }

        [JsonProperty("Video")]
        public string Video { get; set; }

        [JsonProperty("Aspect")]
        public string Aspect { get; set; }

        [JsonProperty("LastFrame")]
        public string LastFrame { get; set; }

        [JsonProperty("AudioAdjust")]
        public string AudioAdjust { get; set; }

        [JsonProperty("AudioAdjustV42")]
        public string AudioAdjustV42 { get; set; }

        [JsonProperty("AudioAdjustMini")]
        public string AudioAdjustMini { get; set; }

        [JsonProperty("AudioAdjustGrid")]
        public string AudioAdjustGrid { get; set; }

        [JsonProperty("AudioAdjustPreview")]
        public string AudioAdjustPreview { get; set; }

        [JsonProperty("AudioAdjustFile")]
        public string AudioAdjustFile { get; set; }

        [JsonProperty("MultipleAudioChannelsSupport")]
        public string MultipleAudioChannelsSupport { get; set; }
    }

    public class VideoFeedback
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }

        [JsonProperty("EnabledPack")]
        public string EnabledPack { get; set; }

        [JsonProperty("Port")]
        public string Port { get; set; }

        [JsonProperty("PortPack")]
        public string PortPack { get; set; }
    }

    public class WebREncoder
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }

        [JsonProperty("M3U8N")]
        public string M3U8N { get; set; }

        [JsonProperty("M3U8D")]
        public string M3U8D { get; set; }
    }

    public class FecTransport
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }

        [JsonProperty("RpcServerIp")]
        public string RpcServerIp { get; set; }

        [JsonProperty("RpcServerPort")]
        public string RpcServerPort { get; set; }
    }

    public class Setting
    {

        [JsonProperty("PreconfiguredBitrate")]
        public string PreconfiguredBitrate { get; set; }

        [JsonProperty("PreconfiguredDelay")]
        public string PreconfiguredDelay { get; set; }
    }

    public class Compose
    {

        [JsonProperty("GroupUrl")]
        public string GroupUrl { get; set; }
    }

    public class Alert
    {

        [JsonProperty("Compose")]
        public Compose Compose { get; set; }
    }

    public class AutoRecord
    {

        [JsonProperty("Transcoder")]
        public string Transcoder { get; set; }

        [JsonProperty("FileRecord")]
        public string FileRecord { get; set; }
    }

    public class LogoOverlay
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }
    }

    public class Logo
    {

        [JsonProperty("IsLogoEnabled")]
        public string IsLogoEnabled { get; set; }

        [JsonProperty("XOffset")]
        public string XOffset { get; set; }

        [JsonProperty("IsEnabled")]
        public string IsEnabled { get; set; }
    }

    public class LiveEncoder
    {

        [JsonProperty("StartPort")]
        public string StartPort { get; set; }

        [JsonProperty("Logo")]
        public Logo Logo { get; set; }
    }

    public class Logo2
    {

        [JsonProperty("FileName")]
        public string FileName { get; set; }
    }

    public class ExEncoder
    {

        [JsonProperty("Logo")]
        public Logo2 Logo { get; set; }
    }

    public class Source
    {

        [JsonProperty("SharedMemoryType")]
        public string SharedMemoryType { get; set; }
    }

    public class DeckLink2
    {

        [JsonProperty("IsSDIOutputEnabled")]
        public string IsSDIOutputEnabled { get; set; }

        [JsonProperty("CardNumber")]
        public string CardNumber { get; set; }
    }

    public class OutputPreview
    {

        [JsonProperty("DeckLink")]
        public DeckLink2 DeckLink { get; set; }

        [JsonProperty("Gop")]
        public string Gop { get; set; }

        [JsonProperty("M3U8N")]
        public string M3U8N { get; set; }

        [JsonProperty("M3U8D")]
        public string M3U8D { get; set; }

        [JsonProperty("VBitrate")]
        public string VBitrate { get; set; }
    }

    public class InputPreview
    {

        [JsonProperty("Gop")]
        public string Gop { get; set; }

        [JsonProperty("M3U8N")]
        public string M3U8N { get; set; }

        [JsonProperty("M3U8D")]
        public string M3U8D { get; set; }

        [JsonProperty("VBitrate")]
        public string VBitrate { get; set; }
    }

    public class Logo3
    {

        [JsonProperty("FileName")]
        public string FileName { get; set; }

        [JsonProperty("XOffset")]
        public string XOffset { get; set; }

        [JsonProperty("YOffset")]
        public string YOffset { get; set; }
    }

    public class Producer
    {

        [JsonProperty("Source")]
        public Source Source { get; set; }

        [JsonProperty("OutputPreview")]
        public OutputPreview OutputPreview { get; set; }

        [JsonProperty("InputPreview")]
        public InputPreview InputPreview { get; set; }

        [JsonProperty("Logo")]
        public Logo3 Logo { get; set; }
    }

    public class WebSite
    {

        [JsonProperty("EnableWebControl")]
        public string EnableWebControl { get; set; }
    }

    public class R2TPDSWrapper
    {

        [JsonProperty("WrapR2TPDS")]
        public string WrapR2TPDS { get; set; }
    }

    public class TokenSystem
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }
    }

    public class SmartCaption
    {

        [JsonProperty("LineCount")]
        public string LineCount { get; set; }

        [JsonProperty("LanguageCode")]
        public string LanguageCode { get; set; }

        [JsonProperty("LineLength")]
        public string LineLength { get; set; }

        [JsonProperty("Enable")]
        public string Enable { get; set; }

        [JsonProperty("DelaySecond")]
        public string DelaySecond { get; set; }
    }

    public class Ftp
    {

        [JsonProperty("Enabled")]
        public string Enabled { get; set; }
    }

    public class Live
    {

        [JsonProperty("OverrideFlag")]
        public string OverrideFlag { get; set; }
    }

    public class Input
    {

        [JsonProperty("Live")]
        public Live Live { get; set; }
    }

    public class GridEncoder
    {

        [JsonProperty("Input")]
        public Input Input { get; set; }
    }

    public class WebRTC
    {

        [JsonProperty("MicrophoneName")]
        public string MicrophoneName { get; set; }

        [JsonProperty("SpeakerName")]
        public string SpeakerName { get; set; }
    }

    public class Capture
    {

        [JsonProperty("DeviceName")]
        public string DeviceName { get; set; }
    }

    public class IFB
    {

        [JsonProperty("Capture")]
        public Capture Capture { get; set; }
    }
}

